services:
  app:
    build: .
    container_name: python-dev
    restart: unless-stopped
    volumes:
      - ./app:/app/app
    command: watchmedo auto-restart --directory=./app --pattern="*.py" --recursive -- python app/main.py